config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'lists', to: 'lists#index'
  # get 'lists/new', to: 'lists#new'
  # post 'lists', to: 'lists#create'
  # get 'lists/:id', to: 'lists#show', as: 'list'

  # get 'lists/:list_id/bookmarks', to: 'bookmarks#index'
  # get 'lists/:list_id/bookmarks/new', to:

  root to: 'lists#index'
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: :create
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  # def new
  #   @list = List.find(params[:list_id])
  #   @bookmark = Bookmark.new
  # end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, label_method: :title, value_method: :id %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%# navbar %>
<div class="navbar-lewagon">
<%= image_tag "film_reel.png", height: 36 %>
<%= link_to 'Create a new list', new_list_path %>
</div>

<div class="container">
  <% @lists.each do |list| %>
    <% if list.photo.nil? %>
      <div class="card-category">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% else %>
      <div class="card-category">
      <%# style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 100, crop: :fit')"> %>
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  <% end %>
</div>

<%#
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo, height: 100, crop: :fit %>
        <%# <%= link_to list.name, list_path(list) %>
      <%# </div> %>

app/views/lists/new.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit 'create a list' %>
<% end %>

app/views/lists/show.html.erb
<div class="navbar-lewagon">
<%= image_tag "film_reel.png", height: 36 %>
<%= link_to 'Back to all lists', lists_path %>

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/random')">
  <%= @list.name %><br>
</div>

<%# <div class="d-flex flex-wrap justify-content-around"> %>
<div class="row">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="col-12 col-sm-6 col-lg-3">
      <div class="card-trip my-3">
        <% movie = Movie.find(bookmark.movie_id) %>
        <%= image_tag "#{movie.poster_url}" %>
        <div class="card-infos">
          <div>
            <h2><%= movie.title %></h2>
            <p><%= bookmark.comment  %></p>
          </div>
          <p class="card-delete"><%= link_to 'Delete this bookmark', bookmark_path(bookmark), method: :delete, data: { confirm: "Delete?" } %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%# </div> %>

<div class="container">
  <h3>Add a bookmark to this list</h3>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, label_method: :title, value_method: :id, input_html: { data: { controller: 'select2' }}%>
    <%= f.input :comment %>
    <%= f.button :submit %>
  <% end %>

</div>

<%= link_to 'Back', lists_path %>